fix: added a version parameter (and accompanying tests) to install_eb_cli in order to give the user version options and prevent the orb from failing if a newer version is unsupported by CircleCI

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -15,6 +15,9 @@ jobs:
       executor:
         type: executor
         default:
+      cli-version:
+        type: string
+        default:
     executor: <<parameters.executor>>
     steps:
       - checkout
@@ -25,6 +28,34 @@ jobs:
           name: Verify EB install
           command: |
             command -v eb >/dev/null 2>&1 || { echo >&2 "EB cli failed to install or persist to the path"; exit 1; }
+      - run:
+          name: Test app version
+          environment:
+            EBCLI_INPUT_VERSION: << parameters.cli-version >> 
+          command: |
+            echo "Checking CLI version..."
+            EBCLI_VERSION=$(eb --version)
+            # Uses python to isolate the latest ebcli version number from the pypi json.
+            EBCLI_LATEST_VERSION=$(python3 -c "import json, urllib.request; print(json.load(urllib.request.urlopen('https://pypi.org/pypi/awsebcli/json'))['info']['version'])")"
+            echo "Elastic Beanstalk CLI version: $EBCLI_VERSION"
+            echo "Expected CLI version: $EBCLI_INPUT_VERSION"
+            echo "Latest CLI version: $EBCLI_LATEST_VERSION"
+
+            # Checks if the installed version matches the expected version
+            if [ ! -z "$EBCLI_VERSION" ] && [ ! -z "$EBCLI_INPUT_VERSION" ] && [ ! -z "$EBCLI_LATEST_VERSION" ]; then
+              if [ "$EBCLI_VERSION" == "$EBCLI_INPUT_VERSION" ]; then
+                echo "CLI version matches expected version."
+              elsif [ "$EBCLI_VERSION" == "$EBCLI_LATEST_VERSION" ]; then
+                echo "CLI version matches the expected latest version."
+              else
+                echo "Error: CLI version does not match expected version." >&2
+                exit 1
+              fi
+            else
+              # This error is thrown when either of the above version numbers don't get properly set
+              echo "Error: Something went wrong with the EB installation. Unable to acquire version(s)." >&2
+              exit 1
+            fi
   integration-test-deploy-setup:
     docker:
       - image: cimg/base:current
@@ -48,6 +79,8 @@ workflows:
           matrix:
               parameters:
                 executor: [python, base]
+                # Emtpy string will use latest version, otherwise testing random recent specific versions
+                cli-version: ["", "3.20.5", "3.20.4", "3.20.3"]
           filters: *filters
       - integration-test-deploy-setup:
           context: [CPE-OIDC]
